define(['./collection/at', './collection/countBy', './collection/every', './collection/filter', './collection/find', './collection/findLast', './collection/findWhere', './collection/forEach', './collection/forEachRight', './collection/groupBy', './collection/includes', './collection/indexBy', './collection/invoke', './collection/map', './collection/max', './collection/min', './collection/partition', './collection/pluck', './collection/reduce', './collection/reduceRight', './collection/reject', './collection/sample', './collection/shuffle', './collection/size', './collection/some', './collection/sortBy', './collection/sortByAll', './collection/toArray', './collection/where'], function(at, countBy, every, filter, find, findLast, findWhere, forEach, forEachRight, groupBy, includes, indexBy, invoke, map, max, min, partition, pluck, reduce, reduceRight, reject, sample, shuffle, size, some, sortBy, sortByAll, toArray, where) {

  return {
    'all': every,
    'any': some,
    'at': at,
    'collect': map,
    'contains': includes,
    'countBy': countBy,
    'detect': find,
    'each': forEach,
    'eachRight': forEachRight,
    'every': every,
    'filter': filter,
    'find': find,
    'findLast': findLast,
    'findWhere': findWhere,
    'foldl': reduce,
    'foldr': reduceRight,
    'forEach': forEach,
    'forEachRight': forEachRight,
    'groupBy': groupBy,
    'include': includes,
    'includes': includes,
    'indexBy': indexBy,
    'inject': reduce,
    'invoke': invoke,
    'map': map,
    'max': max,
    'min': min,
    'partition': partition,
    'pluck': pluck,
    'reduce': reduce,
    'reduceRight': reduceRight,
    'reject': reject,
    'sample': sample,
    'select': filter,
    'shuffle': shuffle,
    'size': size,
    'some': some,
    'sortBy': sortBy,
    'sortByAll': sortByAll,
    'toArray': toArray,
    'where': where
  };
});
